services:
  nginx:
    image: nginx:1.27-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 20M

  api1:
    image: ghcr.io/gabriel-br07/rinha-de-backend-2026-dotnet:latest
    platform: linux/amd64
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_EnableDiagnostics=0
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: 155M

  api2:
    image: ghcr.io/gabriel-br07/rinha-de-backend-2026-dotnet:latest
    platform: linux/amd64
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_EnableDiagnostics=0
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: 155M

